---
- name: restore_playbook
  hosts: webserver
  tasks:
    - name: /etc/ansible/facts.d 디렉토리 삭제
      file:
        path: /etc/ansible/facts.d
        state: absent
    
    - name: 웹 서비스 중지
      service: 
        name: httpd
        state: stopped
        enabled: no
    
    - name: 웹 패키지 삭제
      yum:
        name: httpd
        state: absent
