- name: DB 설정
  gather_facts: no
  hosts: databases
  vars:
    db_pkgs:
      - mariadb-server
      - python3-PyMySQL
    db_svc: mariadb
    db_conf_src: http://ansible.example.com/my.cnf.standard
    db_conf_dest: /etc/my.cnf

  tasks:
    # 1) db 패키지 설치
    # 2) db 서비스 기동
    # 3) db 서비스 설정
    # 4) 핸들러

    - name: 1) db 패키지 설치 - mariadb-server, python3-PyMySQL
      yum:
        name: "{{ db_pkgs }}"
        state: present
      notify:
        - set db password
    
    - name: 2) db 서비스 기동
      service:
        name: "{{ db_svc }}"
        state: started
        enabled: yes
    
    - name: 3) db 서비스 설정 - /etc/my.cnf
      get_url:
        url: "{{ db_conf_src }}"
        dest: "{{ db_conf_dest }}"
        owner: mysql
        group: mysql
        force: yes
      notify:
        - restart db service

    
  handlers:
    - name: restart db service
      service:
        name: "{{ db_svc }}"
        state: started
        enabled: yes

    - name: set db password
      mysql_user:
        name: root
        password: soldesk1.