---
- name: 파일 모으기 - /var/log/secure
  hosts: all
  tasks:
    - name: Fetch the /var/log/secure log file from managed hosts
      fetch:
        src: /var/log/secure
        dest: secure-backups
        flat: no