---
- name: Restore intranet.yml
  hosts: all
  tasks:
    # 1) 방화벽 포트 내리기 - http, https
    # 2) 서비스 중지 - httpd, firewalld
    # 3) 서비스 설정 파일 제거 - /var/www/html/index.html
    # 4) 패키지 삭제 - httpd, mod_ssl, firewalld
    - name: 방화벽 포트 내리기
      firewalld:
        service: "{{ item }}"
        permanent: yes
        immediate: no
        state: disabled
      loop:
        - http
        - https

    - name: 서비스 중지
      service:
        name: "{{ item }}"
        state: stopped
        enabled: no
      loop:
       - httpd
       - firewalld

    - name: 서비스 설정파일 제거
      file:
        path: /var/www/html/index.html
        state: absent

    - name: 패키지 삭제
      yum:
        name:
          - httpd
          - firewalld
        state: absent
      ignore_errors: yes




      