---
# 1) 패키지 설치 - httpd, mariadb(facts)
# 2) db 서비스 기동
# 3) 웹 서비스 기동
- name: 패키지 설치 - httpd, mariadb
  yum:
    name:
      - "{{ ansible_local.custom.packages.db_package }}"
      - "{{ ansible_local.custom.packages.web_package }}"
    state: latest

- name: DB서비스 기동 - mariadb
  service:
    name: "{{ ansible_local.custom.services.db_service }}"
    state: started
    enabled: yes

- name: WEB 서비스 기동 - httpd
  service:
    name: "{{ ansible_local.custom.services.web_service }}"
    state: started
    enabled: yes
    