---
- name: DB 기동하기
  hosts: database_dev
  vars:
    mariadb_packaeges:
      - mariadb-server
      - python3-PyMySQL
    mariadb_service: mariadb
  tasks:
    # 1) DB 패키지 설치 - mariadb-server, python3-PyMySQL
    - name: 1) DB 패키지 설치 - mariadb-server, python3-PyMySQL
      yum:
        name: "{{ item }}"
        state: present
      with_items: "{{ mariadb_packaeges }}"

    - name: DB 서비스 기동
      service:
        name: "{{ mariadb_service }}"
        state: started
        enabled: yes